
package Abscence;


import Admin.*;
import Stagiaire.BD_stagiaire;
import historique.BD_historique;
import historique.historique;
import java.awt.Dimension;
import java.awt.Toolkit;
import static java.nio.file.Files.size;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import forms.Authentification;
import forms.gestion_abscence;
import forms.gestion_admin;


import javax.swing.JOptionPane;

public class modifier_abscence extends javax.swing.JFrame {

    BD_stagiaire bd;
    BD_admin Bd;
    BD_historique BD;

      BD_Abscence base;
    String currentuser;
    ArrayList<String> CIN = new ArrayList<String>();

    public modifier_abscence() throws Exception {
        initComponents();
        this.setFocusable(true);
        Bd = new BD_admin("localhost", 3306, "Gestion_Stages", "root", "");
        bd = new BD_stagiaire("localhost", 3306, "Gestion_Stages", "root", "");
        BD = new BD_historique("localhost", 3306, "Gestion_Stages", "root", "");
       
         base = new BD_Abscence("localhost", 3306, "Gestion_Stages", "root", "");
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
 setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rounde3 = new javaswingdev.swing.rounde();
        panel1 = new javax.swing.JPanel();
        debut = new com.toedter.calendar.JDateChooser();
        fin = new com.toedter.calendar.JDateChooser();
        fermer = new com.k33ptoo.components.KButton();
        enregistrer = new com.k33ptoo.components.KButton();
        cause = new javaswingdev.swing.rounde();
        cin = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        rounde3.setText("rounde1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        debut.setDateFormatString("yyyy-MM-dd");

        fin.setDateFormatString("yyyy-MM-dd");

        fermer.setForeground(new java.awt.Color(0, 0, 0));
        fermer.setText("Fermer");
        fermer.setBorderPainted(false);
        fermer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fermer.setkAllowTab(true);
        fermer.setkBackGroundColor(new java.awt.Color(143, 148, 251));
        fermer.setkBorderRadius(50);
        fermer.setkEndColor(new java.awt.Color(143, 148, 251));
        fermer.setkForeGround(new java.awt.Color(0, 0, 0));
        fermer.setkHoverColor(new java.awt.Color(143, 148, 251));
        fermer.setkHoverEndColor(new java.awt.Color(143, 148, 251));
        fermer.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        fermer.setkHoverStartColor(new java.awt.Color(143, 148, 251));
        fermer.setkIndicatorColor(new java.awt.Color(143, 148, 251));
        fermer.setkPressedColor(new java.awt.Color(143, 148, 251));
        fermer.setkSelectedColor(new java.awt.Color(143, 148, 251));
        fermer.setkStartColor(new java.awt.Color(143, 148, 251));
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });

        enregistrer.setForeground(new java.awt.Color(0, 0, 0));
        enregistrer.setText("Enregistrer");
        enregistrer.setBorderPainted(false);
        enregistrer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enregistrer.setkAllowTab(true);
        enregistrer.setkBackGroundColor(new java.awt.Color(143, 148, 251));
        enregistrer.setkBorderRadius(50);
        enregistrer.setkEndColor(new java.awt.Color(143, 148, 251));
        enregistrer.setkForeGround(new java.awt.Color(0, 0, 0));
        enregistrer.setkHoverColor(new java.awt.Color(143, 148, 251));
        enregistrer.setkHoverEndColor(new java.awt.Color(143, 148, 251));
        enregistrer.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        enregistrer.setkHoverStartColor(new java.awt.Color(143, 148, 251));
        enregistrer.setkIndicatorColor(new java.awt.Color(143, 148, 251));
        enregistrer.setkPressedColor(new java.awt.Color(143, 148, 251));
        enregistrer.setkSelectedColor(new java.awt.Color(143, 148, 251));
        enregistrer.setkStartColor(new java.awt.Color(143, 148, 251));
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });

        cause.setText("Cause");
        cause.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                causeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                causeFocusLost(evt);
            }
        });

        cin.setBackground(new java.awt.Color(153, 153, 153));
        cin.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        nom.setBackground(new java.awt.Color(153, 153, 153));
        nom.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CIN : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Nom : ");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(debut, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(fin, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(159, 159, 159))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(cause, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(cause, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(debut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fermer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinActionPerformed

    private void cinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusGained
       if (cin.getText().equals("CIN ")) {
            cin.setText("");
        }
    }//GEN-LAST:event_cinFocusGained

    private void cinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusLost
      if (cin.getText().equals("")) {
            cin.setText("CIN ");
        }
    }//GEN-LAST:event_cinFocusLost

    private void nomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomFocusGained
           if (nom.getText().equals("Nom Complet")) {
            nom.setText("");
        }
    }//GEN-LAST:event_nomFocusGained

    private void nomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomFocusLost
      if (nom.getText().equals("")) {
            nom.setText("Nom Complet");
        }
    }//GEN-LAST:event_nomFocusLost

    private void causeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_causeFocusGained
      if (cause.getText().equals("Cause")) {
            cause.setText("");
      }
    }//GEN-LAST:event_causeFocusGained

    private void causeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_causeFocusLost
 if (cause.getText().equals("")) {
            cause.setText("Cause");
      }        // TODO add your handling code here:
    }//GEN-LAST:event_causeFocusLost

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        this.hide();
    }//GEN-LAST:event_fermerActionPerformed

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
     DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        String date3 = dateFormat.format(debut.getDate());
        String date4= dateFormat.format(fin.getDate());
   
        int nbr_jour = this.nbrjour(date3, date4);
          if (cause.getText().equals("") || cause.getText().equals("Cause")) {
            JOptionPane.showMessageDialog(null, "Cause !",
                    "", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                //if(remarque.getText().equals("Remarque")){
                    base.modifier_abscence(gestion_abscence.idselected,date3,date4,nbr_jour,cause.getText());
                    gestion_abscence.table1.removeall(gestion_abscence.table1);
                    base.getAbscences(gestion_abscence.table1);
                    historique histo = new historique("Modifier Abscence", date);
                    currentuser = Bd.getcurrentAdmin(Authentification.usercurrent);
                    BD.inserthistorique(histo.getId(), currentuser.split("_")[0], histo);
                    this.hide();
                /*}else{
                   Db.modifier_tache(gestion_tache.idselected, tache.getText(),date3, date4, remarque.getText());
                    gestion_tache.table1.removeall(gestion_tache.table1);
                    Db.gettaches(gestion_tache.table1);
                    historique histo = new historique("Modifier Tache", date);
                    currentuser = Bd.getcurrentAdmin(Authentification.usercurrent);
                    BD.inserthistorique(histo.getId(), currentuser.split(" ")[0], currentuser.split(" ")[1], histo);
                    this.hide();
                }*/
            } catch (SQLException ex) {
                Logger.getLogger(modifier_abscence.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_enregistrerActionPerformed

     private int nbrjour(String date1, String date2) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        int res = 0;
        try {
            Date dateAvant = sdf.parse(date1);
            Date dateApres = sdf.parse(date2);
            int diff = (int) (dateApres.getTime() - dateAvant.getTime());
            res = (diff / (1000 * 60 * 60 * 24));
        } catch (Exception e) {
        }
        return res;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifier_abscence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifier_abscence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifier_abscence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifier_abscence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new modifier_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javaswingdev.swing.rounde cause;
    public static javax.swing.JLabel cin;
    public static com.toedter.calendar.JDateChooser debut;
    private com.k33ptoo.components.KButton enregistrer;
    private com.k33ptoo.components.KButton fermer;
    public static com.toedter.calendar.JDateChooser fin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel nom;
    private javax.swing.JPanel panel1;
    private javaswingdev.swing.rounde rounde3;
    // End of variables declaration//GEN-END:variables
}
